f1t/apps/driver_ranks/urls.py
from django.urls import path
from .views import DriverRankListView, DragDropRankView, DriverRanksDetailView, DriverPointsView

app_name = 'driver_ranks'
urlpatterns = [
    path('<str:series>/<int:year>/driver_ranks/', DriverRankListView.as_view(), name='driver-rank-list'),
    path('<str:series>/<int:year>/driver_ranks/new/', DragDropRankView.as_view(), name='driver-rank-form'),
    path('<str:series>/<int:year>/driver_ranks/points/', DriverPointsView.as_view(), name='driver_points'),
    path('<str:series>/<int:year>/driver_ranks/<str:username>/', DriverRanksDetailView.as_view(), name='driver-rank-detail'),
]

f1t/apps/fantasy/urls.py
from django.urls import include, path

from . import views
from .views import JolpicaCheckAPIView

app_name = "formula"
urlpatterns = [
    # Formula paths
    path('circuits/', views.CircuitListView.as_view(), name='circuit_list'),
    path('circuits/<pk>/', views.CircuitDetailView.as_view(), name='circuit_detail'),

    path('drivers/', views.AllDriverListView.as_view(), name='all_driver_list'),
    path('drivers/<slug>/', views.DriverDetailView.as_view(), name='driver_detail'),
    path('drivers/<slug>/races/', views.DriverResultsView.as_view(), name='driver_results'),
    path('drivers/<slug>/wins/', views.DriverWinsView.as_view(), name='driver_wins'),
    path('drivers/<slug>/poles/', views.DriverPolesView.as_view(), name='driver_poles'),
    path('drivers/<slug>/flaps/', views.DriverFastestLapsView.as_view(), name='driver_flaps'),
    path('drivers/<slug>/hattricks/', views.DriverHatTricksView.as_view(), name='driver_hattricks'),
    path('drivers/<slug>/podiums/', views.DriverPodiumsView.as_view(), name='driver_podiums'),
    path('drivers/<slug>/quali_h2h/', views.DriverHeadToHeadView.as_view(), name='driver_quali_h2h'),

    path('constructors/', views.ConstructorListView.as_view(), name='constructor_list'),
    path('constructors/<slug>/', views.ConstructorDetailView.as_view(), name='constructor_detail'),

    # Series Stats
    path('<str:series>/stats/', views.StatsForSeriesView.as_view(), name='stats_series'),
    path('<str:series>/stats/drivers/', views.StatsForDriverTemplateView.as_view(), name='stats_drivers'),
    path('<str:series>/stats/drivers/wins/', views.StatsForDriverWinView.as_view(), name='stats_driver_wins'),
    path('<str:series>/stats/drivers/poles/', views.StatsForDriverPoleView.as_view(), name='stats_driver_poles'),
    path('<str:series>/stats/drivers/podiums/', views.StatsForDriverPodiumView.as_view(), name='stats_driver_podiums'),
    path('<str:series>/stats/drivers/races/', views.StatsForDriverRaceView.as_view(), name='stats_driver_races'),
    path('<str:series>/stats/drivers/without_win/', views.StatsForDriverWithoutWinView.as_view(), name='stats_driver_without_win'),
    path('<str:series>/stats/drivers/finishes/', views.StatsForDriverFinishedView.as_view(), name='stats_driver_finishes'),

    # Season paths
    path('<str:series>/', views.SeasonsListView.as_view(), name='season_list'),
    path('<str:series>/<int:year>/stats/', views.SeasonStatsView.as_view(), name='season_stats'),
    path('<str:series>/<int:year>/stats/supergrid/', views.SeasonSupergridView.as_view(), name='season_supergrid'),
    path('<str:series>/<int:year>/stats/quali_h2h/', views.SeasonHeadToHeadView.as_view(), name='season_quali_h2h'),
    path('<str:series>/<int:year>/', views.RaceListView.as_view(), name='race_list'),
    path('<str:series>/<int:year>/last/', views.LastRaceRedirectView.as_view(), name='redirect_last_race'),
    path('<str:series>/<int:year>/<int:round>/', views.RaceDetailView.as_view(), name='race_detail'),
    path('<str:series>/<int:year>/<int:round>/fantasy/', views.RaceFantasyView.as_view(), name='fantasy_race_results'),
    path('<str:series>/<int:year>/last/fantasy/', views.LastRaceFantasyRedirectView.as_view(), name='redirect_last_fantasy_result'),
    path('<str:series>/<int:year>/<int:round>/edit/', views.RaceDriverUpdateView.as_view(), name='race_edit'),
    path('<str:series>/<int:year>/<int:round>/fantasy/edit/', views.PriceUpdateView.as_view(), name='price_edit'),

    # Fantasy paths
    path('<str:series>/<int:year>/teams/', views.FantasyStandingsView.as_view(), name='team_list_deprecated'),
    path('<str:series>/<int:year>/fantasy/', views.FantasyStandingsView.as_view(), name='team_list'),
    path('<str:series>/<int:year>/fantasy/stats/', views.FantasyStatsView.as_view(), name='driver_stats'),
    path('<str:series>/<int:year>/teams/new/', views.NewTeamView.as_view(), name='new_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/new/', views.NewTeamView.as_view(), name='new_team_form'),
    path('<str:series>/<int:year>/teams/edit/', views.EditTeamView.as_view(), name='edit_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/edit/', views.EditTeamView.as_view(), name='edit_team_form'),
    path('<str:series>/<int:year>/teams/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team_deprecated'),
    path('<str:series>/<int:year>/fantasy/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team'),
    path('<str:series>/<int:year>/teams/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail_deprecated'),
    path('<str:series>/<int:year>/fantasy/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail'),

    # API paths
    path('api/jolpica_check/', JolpicaCheckAPIView.as_view(), name='jolpica-check-api'),

    # Tahmin ligi paths
    path('<str:series>/<int:year>/', include("f1t.apps.tahmin.urls")),
]

f1t/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.conf import settings
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from .views import HomeView, ContactView
from .urlresolvers import solid_i18n_patterns

patterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("f1t.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("contact/", ContactView.as_view(), name='contact'),
    path("greenflag/", include("f1t.apps.greenflag.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("", include("f1t.apps.season_predictions.urls")),
    path("", include("f1t.apps.driver_ranks.urls")),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('pwa.urls')),
    path('', HomeView.as_view(), name='home'),
    path("", include("f1t.apps.fantasy.urls")),
    path("", include("f1t.apps.ratings.urls")),
]

if settings.DEBUG:
    patterns.append(path('__debug__/', include('debug_toolbar.urls')))

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n"))
]
urlpatterns += solid_i18n_patterns(*patterns)

f1t/apps/driver_ranks/models.py
from django.db import models
from django.contrib.auth.models import User

from f1t.apps.fantasy.models import Driver, Championship

class PollResponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    championship = models.ForeignKey(Championship, on_delete=models.CASCADE)
    driver = models.ForeignKey(Driver, on_delete=models.CASCADE)
    position = models.PositiveIntegerField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

f1t/apps/driver_ranks/forms.py
from django import forms

from f1t.apps.fantasy.models import Driver


class DragDropRankForm(forms.Form):
    ranked_drivers = forms.CharField(widget=forms.HiddenInput())

    def clean_ranked_drivers(self):
        data = self.cleaned_data['ranked_drivers']
        try:
            driver_ids = [int(id) for id in data.split(',')]
        except:
            raise forms.ValidationError("Invalid format")

        # Verify all drivers are present and valid
        valid_drivers = set(Driver.objects.filter(
            pk__in=driver_ids
        ).values_list('id', flat=True))

        if len(driver_ids) != 20 or len(set(driver_ids)) != 20:
            raise forms.ValidationError("Invalid driver selection")

        return driver_ids

f1t/apps/driver_ranks/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Sum, Case, When, IntegerField, Q
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import FormView

from .models import PollResponse
from .forms import DragDropRankForm
from f1t.apps.fantasy.models import Championship, Driver, Race

User = get_user_model()
DRIVER_RANK_POINTS = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1, -1, -2, -4, -6, -8, -10, -12, -15, -18, -25]


class DriverPointsView(TemplateView):
    template_name = 'driver_ranks/driver_points.html'

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Create a Case statement to assign points based on position from PollResponse
        point_cases = Case(
            *[When(pollresponse__position=i + 1, then=DRIVER_RANK_POINTS[i]) for i in range(20)],
            default=0,
            output_field=IntegerField()
        )

        driver_points = Driver.objects.annotate(
            total_points=Sum(
                point_cases,
                filter=Q(pollresponse__championship=self.championship)
            )
        ).filter(
            total_points__isnull=False
        ).order_by('-total_points')

        context['driver_points'] = driver_points
        return context


class DragDropRankView(SuccessMessageMixin, LoginRequiredMixin, FormView):
    template_name = 'driver_ranks/drag_drop.html'
    form_class = DragDropRankForm
    success_message = "Sürücü sıralamanız başarıyla kaydedildi."

    def get_success_url(self):
        return self.request.path

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        # Fetch the championship object
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )

    def _is_past_deadline(self):
        try:
            race = self.championship.races.earliest("fp1_datetime")
            deadline = race.fp1_datetime
            return timezone.now() > deadline
        except Race.DoesNotExist:
            return True

    def get(self, request, *args, **kwargs):
        if self._is_past_deadline():
            return render(request, "expired.html", status=403)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if self._is_past_deadline():
            return render(request, "expired.html", status=403)
        return super().post(request, *args, **kwargs)

    def get_queryset(self):
        return Driver.objects.filter(
            race_instances__race__championship=self.championship
        ).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        race = self.championship.races.earliest("fp1_datetime")
        # Get base queryset
        drivers = self.get_queryset()

        # Check for existing poll response
        if self.request.user.is_authenticated:
            existing_response = PollResponse.objects.filter(
                user=self.request.user,
                championship=self.championship
            ).order_by('position')

            if existing_response.exists():
                # Get driver IDs in existing order
                ordered_ids = existing_response.values_list('driver_id', flat=True)

                # Preserve the order from the existing response
                preserved_order = Case(
                    *[When(id=driver_id, then=pos) for pos, driver_id in enumerate(ordered_ids)],
                    output_field=IntegerField()
                )
                drivers = drivers.order_by(preserved_order)
        context['drivers'] = drivers
        context['deadline'] = race.fp1_datetime
        return context

    def form_valid(self, form):
        driver_ids = form.cleaned_data['ranked_drivers']
        user = self.request.user
        user.pollresponse_set.filter(
            championship=self.championship
        ).delete()

        for position, driver_id in enumerate(driver_ids, start=1):
            PollResponse.objects.create(
                user=self.request.user,
                championship=self.championship,
                driver_id=driver_id,
                position=position
            )
        return super().form_valid(form)


class DriverRanksDetailView(DetailView):
    model = PollResponse
    template_name = 'driver_ranks/detail.html'
    context_object_name = 'user'

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        # Fetch the championship object
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )

    def get_object(self):
        return get_object_or_404(
            User,
            username=self.kwargs.get('username')
        )

    def _is_past_deadline(self):
        try:
            race = self.championship.races.earliest("fp1_datetime")
            deadline = race.fp1_datetime
            return timezone.now() > deadline
        except Race.DoesNotExist:
            return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        user_responses = user.pollresponse_set.select_related('driver').filter(
            championship=self.championship
        ).order_by('position')

        context['processed_answers'] = user_responses
        return context


class DriverRankListView(ListView):
    template_name = 'driver_ranks/list.html'
    context_object_name = 'users'
    allow_empty = False

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        # Fetch the championship object
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )
    def get_queryset(self):
        return User.objects.filter(
            pollresponse__championship=self.championship
        ).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['championship'] = self.championship
        return context

f1t/apps/driver_ranks/templates/driver_ranks/detail.html
{% extends "base.html" %}
{% load custom_filters static %}

{% block title %}{{ user }} - {{ view.championship.get_series_display }} {{ view.championship.year }} Sürücü Sevgi Sıralamaları{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.championship.series %}">{{ view.championship.get_series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:race_list' view.championship.series view.championship.year %}">{{ view.championship.year }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'driver_ranks:driver-rank-list' view.championship.series view.championship.year %}">Sürücü Sevgi Sıralamaları</a></li>
    <li class="breadcrumb-item">{{ user.get_full_name }}</li>
{% endblock %}}

{% block stylesheet %}
    <style>
        .driver-item {
            padding: 3px;
            margin: 5px;
            display: flex;
            align-items: center;
            gap: 15px;
        }

        .position-badge {
            width: 30px;
            height: 30px;
            background: #007bff;
            color: white;
            border-radius: 50%;
            display: flex;
            align-items: center;
            justify-content: center;
            font-weight: bold;
        }
    </style>
{% endblock %}

{% block content %}
    <div class="card">
        <div class="card-body">
            {% for answer in processed_answers %}
                <div class="driver-item" data-id="{{ driver.id }}">
                    <div class="position-badge">{% widthratio forloop.counter 1 1 %}</div>
                    {{ answer.driver }}
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}

f1t/apps/driver_ranks/templates/driver_ranks/drag_drop.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ view.championship.get_series_display }} {{ view.championship.year }} Sürücü Sevgi Sıralamaları Formu{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.championship.series %}">{{ view.championship.get_series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:race_list' view.championship.series view.championship.year %}">{{ view.championship.year }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'driver_ranks:driver-rank-list' view.championship.series view.championship.year %}">Sürücü Sevgi Sıralamaları</a></li>
    <li class="breadcrumb-item">Form</li>
{% endblock %}

{% block stylesheet %}
<style>
    .driver-list {
        list-style: none;
        padding: 0;
    }

    .driver-item {
        padding: 10px;
        margin: 5px;
        background: #f8f9fa;
        border: 1px solid #dee2e6;
        border-radius: 4px;
        cursor: move;
        display: flex;
        align-items: center;
        gap: 15px;
    }

    .position-badge {
        width: 30px;
        height: 30px;
        background: #007bff;
        color: white;
        border-radius: 50%;
        display: flex;
        align-items: center;
        justify-content: center;
        font-weight: bold;
    }
</style>
{% endblock %}

{% block content %}
    <h1 class="mb-4 text-center">{{ view.championship.get_series_display }} {{ view.championship.year }} Sürücü Sevgi Sıralaması Formu</h1>
    <ul>
        <li>Sıralamayı oluşturmak için sürücüleri fareyle ya da parmaklarınızla sürücüleri sürükleyip bırakın.</li>
        <li>İşlemlerinizi <b>{{ deadline|default_if_none:"???" }}</b> tarihine kadar yapabilirsiniz.</li>
    </ul>

  <form method="post" id="ranking-form">
    {% csrf_token %}
    {{ form.ranked_drivers }}

    <div id="driver-list">
        {% for driver in drivers %}
        <div class="driver-item" data-id="{{ driver.id }}">
            <div class="position-badge">{% widthratio forloop.counter 1 1 %}</div>
            {{ driver.name }}
        </div>
        {% endfor %}
    </div>

      <button type="submit" class="btn btn-success">Gönder</button>
</form>


{% endblock %}

{% block javascript %}
    <script src="https://cdn.jsdelivr.net/npm/sortablejs@1.15.6/Sortable.min.js"></script>
    <script>
document.addEventListener('DOMContentLoaded', function() {
    const form = document.getElementById('ranking-form');
    const driverList = document.getElementById('driver-list');
    const hiddenInput = document.querySelector('#id_ranked_drivers');

    // Initialize Sortable
    const sortable = new Sortable(driverList, {
        animation: 150,
        ghostClass: 'sortable-ghost',
        onUpdate: function() {
            updatePositions();
            updateHiddenInput();
        }
    });

    function updatePositions() {
        driverList.querySelectorAll('.driver-item').forEach((item, index) => {
            item.querySelector('.position-badge').textContent = index + 1;
        });
    }

    function updateHiddenInput() {
        const driverIds = Array.from(driverList.children).map(
            item => item.dataset.id
        );
        hiddenInput.value = driverIds.join(',');
    }

    // Initial setup
    updateHiddenInput();

    // Handle form submission
    form.addEventListener('submit', function(e) {
        if (!hiddenInput.value) {
            e.preventDefault();
            alert('Please arrange the drivers before submitting!');
        }
    });
});
</script>
{% endblock %}

f1t/apps/driver_ranks/templates/driver_ranks/driver_points.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title %}{{ view.championship.get_series_display }} {{ view.championship.year }} Sürücü Sevgi Sıralamaları{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.championship.series %}">{{ view.championship.get_series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:race_list' view.championship.series view.championship.year %}">{{ view.championship.year }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'driver_ranks:driver-rank-list' view.championship.series view.championship.year %}">Sürücü Sevgi Sıralamaları</a></li>
    <li class="breadcrumb-item">Sürücü Puanları</li>
{% endblock %}

{% block content %}
    <div class="table-responsive">
        <table id="driver_ranks_table"
               class="table table-borderless d-block stripe hover cell-border order-column justify-content-center text-center text-nowrap">
            <thead class="table-light">
            <tr>
                <th>Driver</th>
                <th>Total Points</th>
            </tr>
            </thead>
            <tbody>
            {% for driver in driver_points %}
                <tr>
                    <td>{{ driver.name }}</td>
                    <td>{{ driver.total_points }}</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
    </div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#driver_ranks_table").DataTable(
                {
                    language: {
                        "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json"
                    },
                    paging: true,
                    pageLength: 50,
                    "order": [],
                    "info": false,
                    columnDefs: [
                        {
                            className: "dt-center",
                            targets: "_all"
                        }
                    ]
                }
            );
        });
    </script>
{% endblock %}

f1t/apps/driver_ranks/templates/driver_ranks/list.html
{% extends "base.html" %}
{% load custom_filters %}

{% block title %}{{ view.championship.get_series_display }} {{ view.championship.year }} Sürücü Sevgi Sıralamaları{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.championship.series %}">{{ view.championship.get_series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:race_list' view.championship.series view.championship.year %}">{{ view.championship.year }}</a></li>
    <li class="breadcrumb-item">Sürücü Sevgi Sıralamaları</li>
{% endblock %}}


{% block content %}
    <div class="d-flex justify-content-between my-4">
        <a class="btn btn-outline-primary {% if not championship.previous %}disabled{% endif %}" href="{% if not championship.previous %}#{% else %}{% url 'driver_ranks:driver-rank-list' championship.series championship.previous.year %}{% endif %}">&larr; {{ championship.previous.short_str|upper|default_if_none:"" }}</a>
        <h3 class="text-center">{{ championship.short_str|upper }} Sürücü Sevgi Sıralamaları</h3>
        <a class="btn btn-outline-primary {% if not championship.next %}disabled{% endif %}" href="{% if not championship.next %}#{% else %}{% url 'driver_ranks:driver-rank-list' championship.series championship.next.year %}{% endif %}">{{ championship.next.short_str|upper|default_if_none:"" }} &rarr;</a>
    </div>
    <div class="d-flex gap-2 mb-4" role="toolbar" aria-label="Toolbar with button groups">
        <a href="{% url 'driver_ranks:driver-rank-form' view.championship.series view.championship.year %}"
           class="btn btn-outline-primary {% if request.device.is_mobile %}btn-sm{% endif %}"><i
            class="fa-solid fa-list-ol"></i> Ankete Git</a>
    </div>
    <div class="table-responsive">
    <table id="driver_ranks_table"
        class="table table-borderless d-block stripe hover cell-border order-column justify-content-center text-center text-nowrap">
        <thead class="table-light">
            <tr>
                <th>Üye</th>
            </tr>
        </thead>
        <tbody>
            {% for user in users %}
            <tr>
                <td>
                    <a href="{% url 'driver_ranks:driver-rank-detail' championship.series championship.year user.username %}">
                        {{ user.get_full_name }}
                    </a>
                </td>
            </tr>
            {% empty %}
            <tr>
                <td colspan="3" class="text-center">Henüz hiçbir üye tahmin yapmadı.</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $("#driver_ranks_table").DataTable(
                {
                    language: {
                        "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json"
                    },
                    paging: true,
                    pageLength: 50,
                    "order": [],
                    "info": false,
                    columnDefs: [
                        {
                            className: "dt-center",
                            targets: "_all"
                        }
                    ]
                }
            );
        });
    </script>
{% endblock %}