f1t/apps/fantasy/urls.py
from django.urls import include, path

from . import views
from .views import JolpicaCheckAPIView

app_name = "formula"
urlpatterns = [
    # Formula paths
    path('circuits/', views.CircuitListView.as_view(), name='circuit_list'),
    path('circuits/<pk>/', views.CircuitDetailView.as_view(), name='circuit_detail'),

    path('drivers/', views.AllDriverListView.as_view(), name='all_driver_list'),
    path('drivers/<slug>/', views.DriverDetailView.as_view(), name='driver_detail'),
    path('drivers/<slug>/races/', views.DriverResultsView.as_view(), name='driver_results'),
    path('drivers/<slug>/wins/', views.DriverWinsView.as_view(), name='driver_wins'),
    path('drivers/<slug>/poles/', views.DriverPolesView.as_view(), name='driver_poles'),
    path('drivers/<slug>/flaps/', views.DriverFastestLapsView.as_view(), name='driver_flaps'),
    path('drivers/<slug>/hattricks/', views.DriverHatTricksView.as_view(), name='driver_hattricks'),
    path('drivers/<slug>/podiums/', views.DriverPodiumsView.as_view(), name='driver_podiums'),
    path('drivers/<slug>/quali_h2h/', views.DriverHeadToHeadView.as_view(), name='driver_quali_h2h'),

    path('constructors/', views.ConstructorListView.as_view(), name='constructor_list'),
    path('constructors/<slug>/', views.ConstructorDetailView.as_view(), name='constructor_detail'),

    # Series Stats
    path('<str:series>/stats/', views.StatsForSeriesView.as_view(), name='stats_series'),
    path('<str:series>/stats/drivers/', views.StatsForDriverTemplateView.as_view(), name='stats_drivers'),
    path('<str:series>/stats/drivers/wins/', views.StatsForDriverWinView.as_view(), name='stats_driver_wins'),
    path('<str:series>/stats/drivers/poles/', views.StatsForDriverPoleView.as_view(), name='stats_driver_poles'),
    path('<str:series>/stats/drivers/podiums/', views.StatsForDriverPodiumView.as_view(), name='stats_driver_podiums'),
    path('<str:series>/stats/drivers/races/', views.StatsForDriverRaceView.as_view(), name='stats_driver_races'),
    path('<str:series>/stats/drivers/without_win/', views.StatsForDriverWithoutWinView.as_view(), name='stats_driver_without_win'),
    path('<str:series>/stats/drivers/finishes/', views.StatsForDriverFinishedView.as_view(), name='stats_driver_finishes'),

    # Season paths
    path('<str:series>/', views.SeasonsListView.as_view(), name='season_list'),
    path('<str:series>/<int:year>/stats/', views.SeasonStatsView.as_view(), name='season_stats'),
    path('<str:series>/<int:year>/stats/supergrid/', views.SeasonSupergridView.as_view(), name='season_supergrid'),
    path('<str:series>/<int:year>/stats/quali_h2h/', views.SeasonHeadToHeadView.as_view(), name='season_quali_h2h'),
    path('<str:series>/<int:year>/', views.RaceListView.as_view(), name='race_list'),
    path('<str:series>/<int:year>/last/', views.LastRaceRedirectView.as_view(), name='redirect_last_race'),
    path('<str:series>/<int:year>/<int:round>/', views.RaceDetailView.as_view(), name='race_detail'),
    path('<str:series>/<int:year>/<int:round>/fantasy/', views.RaceFantasyView.as_view(), name='fantasy_race_results'),
    path('<str:series>/<int:year>/last/fantasy/', views.LastRaceFantasyRedirectView.as_view(), name='redirect_last_fantasy_result'),
    path('<str:series>/<int:year>/<int:round>/edit/', views.RaceDriverUpdateView.as_view(), name='race_edit'),
    path('<str:series>/<int:year>/<int:round>/fantasy/edit/', views.PriceUpdateView.as_view(), name='price_edit'),

    # Fantasy paths
    path('<str:series>/<int:year>/teams/', views.FantasyStandingsView.as_view(), name='team_list_deprecated'),
    path('<str:series>/<int:year>/fantasy/', views.FantasyStandingsView.as_view(), name='team_list'),
    path('<str:series>/<int:year>/fantasy/stats/', views.FantasyStatsView.as_view(), name='driver_stats'),
    path('<str:series>/<int:year>/teams/new/', views.NewTeamView.as_view(), name='new_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/new/', views.NewTeamView.as_view(), name='new_team_form'),
    path('<str:series>/<int:year>/teams/edit/', views.EditTeamView.as_view(), name='edit_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/edit/', views.EditTeamView.as_view(), name='edit_team_form'),
    path('<str:series>/<int:year>/teams/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team_deprecated'),
    path('<str:series>/<int:year>/fantasy/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team'),
    path('<str:series>/<int:year>/teams/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail_deprecated'),
    path('<str:series>/<int:year>/fantasy/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail'),

    # API paths
    path('api/jolpica_check/', JolpicaCheckAPIView.as_view(), name='jolpica-check-api'),

    # Tahmin ligi paths
    path('<str:series>/<int:year>/', include("f1t.apps.tahmin.urls")),
]

f1t/apps/ratings/urls.py
from django.urls import include, path

from . import views

app_name = "ratings"
urlpatterns = [
    # Yarışı Puanla paths
    path('<str:series>/<int:year>/puanla/', views.SeasonRatingView.as_view(), name='season_ratings'),
    path('<str:series>/puanla/', views.SeriesRatingView.as_view(), name='series_ratings'),
    path('<str:series>/<int:year>/<int:round>/puanla/', views.RatingCreateView.as_view(), name='create_ratings'),
]

f1t/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.conf import settings
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from .views import HomeView, ContactView
from .urlresolvers import solid_i18n_patterns

patterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("f1t.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("contact/", ContactView.as_view(), name='contact'),
    path("greenflag/", include("f1t.apps.greenflag.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("", include("f1t.apps.season_predictions.urls")),
    path("", include("f1t.apps.driver_ranks.urls")),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('pwa.urls')),
    path('', HomeView.as_view(), name='home'),
    path("", include("f1t.apps.fantasy.urls")),
    path("", include("f1t.apps.ratings.urls")),
]

if settings.DEBUG:
    patterns.append(path('__debug__/', include('debug_toolbar.urls')))

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n"))
]
urlpatterns += solid_i18n_patterns(*patterns)

f1t/apps/fantasy/models.py
import json
from decimal import Decimal
from functools import cache
from math import ceil
from pathlib import Path

from django.contrib.auth.models import User
from django.core.validators import RegexValidator
from django.db import models
from django.db.models import OuterRef, Subquery
from django.urls import reverse
from django.utils import timezone
from django.utils.functional import cached_property
from django.utils.text import slugify
from django_countries.fields import CountryField
from colorfield.fields import ColorField

JSON_PATH = Path(__file__).parent / "points.json"
with JSON_PATH.open() as json_file:
    POINTS = json.load(
        json_file,
        object_pairs_hook=lambda pairs: {int(k) if k.isnumeric() else k: v for k, v in pairs}
    )


QUALI_TIME_VALIDATOR = RegexValidator(
    regex=r'^(?:\d{1,2}:[0-5]\d\.\d{1,3})?$',
    message="Enter a valid qualifying time format (e.g., '1:21.072' or leave it blank)."
)

def convert_to_float(value):
    """Convert 'minutes:seconds.milliseconds' string to total seconds as a float."""
    if not value:
        return None
    try:
        # Split the string into minutes and seconds
        minutes, seconds = value.split(':')
        # Convert to total seconds
        total_seconds = float(minutes) * 60 + float(seconds)
        return total_seconds
    except ValueError:
        return None

class Championship(models.Model):
    CHAMPIONSHIP_CHOICES = [
        ("f1", "Formula 1"),
        ("f2", "Formula 2"),
        ("fe", "Formula E"),
    ]
    year = models.IntegerField()
    series = models.CharField(
        max_length=255,
        choices=CHAMPIONSHIP_CHOICES
    )
    is_fantasy = models.BooleanField(default=False)
    is_tahmin = models.BooleanField(default=False)
    is_sprint_overtake_point = models.BooleanField(default=False)
    is_feature_overtake_point = models.BooleanField(default=True)
    fastest_lap_point_threshold = models.PositiveSmallIntegerField(default=10)
    sprint_fastest_lap_point_threshold = models.PositiveSmallIntegerField(default=10)
    fastest_lap_point = models.PositiveSmallIntegerField(default=0)
    sprint_fastest_lap_point = models.PositiveSmallIntegerField(default=0)
    pole_point = models.PositiveSmallIntegerField(default=0)
    qualy_fantasy_h2h_point = models.PositiveSmallIntegerField(default=0)
    race_fantasy_h2h_point = models.PositiveSmallIntegerField(default=0)
    overtake_coefficient = models.FloatField()
    qualifying_coefficient = models.FloatField()
    finish_coefficient = models.FloatField()
    beginning_token = models.PositiveSmallIntegerField()
    starting_budget = models.DecimalField(max_digits=3, decimal_places=1)
    max_drivers_in_team = models.PositiveSmallIntegerField(default=8)
    slug = models.SlugField(unique=True, editable=False)

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['year', 'series'], name='unique_year_series'),
        ]
        ordering = ["-year", "series"]

    def __str__(self):
        return f"{self.year} {self.get_series_display()} Şampiyonası"

    def short_str(self):
        return f"{self.year} {self.series}"

    def is_puanla(self):
        return self.races.filter(rating_instance__isnull=False).exists()

    def is_season_predictions(self):
        return self.question_set.exists()

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = f"{self.year}-{self.series}"
        super().save(*args, **kwargs)

    def coefficient(self, tactic):
        if tactic == RaceTeam.GEÇİŞ:
            return self.overtake_coefficient
        elif tactic == RaceTeam.SIRALAMA:
            return self.qualifying_coefficient
        elif tactic == RaceTeam.FİNİŞ:
            return self.finish_coefficient

    @cached_property
    def next(self):
        try:
            return Championship.objects.get(series=self.series, year=self.year + 1)
        except Championship.DoesNotExist:
            return None

    @cached_property
    def previous(self):
        try:
            return Championship.objects.get(series=self.series, year=self.year - 1)
        except Championship.DoesNotExist:
            return None

    def latest_race(self):
        try:
            return self.races.filter(
                datetime__lt=timezone.now()
            ).latest("datetime")
        except Race.DoesNotExist:
            return None

    def next_race(self, league):
        try:
            if league == "fantasy":
                return self.races.filter(
                    fp1_datetime__gt=timezone.now(),
                    fantasy_ready=True
                ).latest("fp1_datetime")
            elif league == "tahmin":
                return self.races.filter(
                    datetime__gt=timezone.now(),
                    quali_datetime__lt=timezone.now()
                ).latest("quali_datetime")
        except Race.DoesNotExist:
            return None

    def get_absolute_url(self):
        return reverse("formula:race_list", kwargs={'series': self.series, 'year': self.year})


class Circuit(models.Model):
    slug = models.SlugField(primary_key=True)
    name = models.CharField(max_length=255)
    location = models.CharField(max_length=255, null=True, blank=True)
    country = CountryField(null=True, blank=True)
    latitude = models.FloatField(null=True, blank=True)
    longitude = models.FloatField(null=True, blank=True)
    url = models.URLField(unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("formula:circuit_detail", kwargs={'pk': self.pk})


class Constructor(models.Model):
    name = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, editable=False)
    country = CountryField(null=True, blank=True)
    url = models.URLField(null=True, blank=True)
    championship = models.ManyToManyField(Championship, through='ChampionshipConstructor', related_name='constructors')

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("formula:constructor_detail", kwargs={'slug': self.slug})


class Driver(models.Model):
    forename = models.CharField(max_length=255)
    surname = models.CharField(max_length=255)
    slug = models.SlugField(unique=True, editable=False)
    number = models.IntegerField(blank=True, null=True)
    code = models.CharField(max_length=3, blank=True, null=True)
    country = CountryField(null=True, blank=True)
    dob = models.DateField(blank=True, null=True)
    url = models.URLField(null=True, blank=True)

    class Meta:
        ordering = ["forename", "surname"]

    def __str__(self):
        return self.name

    @property
    def name(self):
        return f"{self.forename} {self.surname}"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse("formula:driver_detail", kwargs={'slug': self.slug})

    def age(self):
        """Calculate the age of someone with floating point precision"""
        if self.dob is None:
            return

        today = timezone.now().date()  # Get the current date from timezone-aware datetime
        birthdate = self.dob
        # Calculate the birthday in the current year
        try:
            birthday = birthdate.replace(year=today.year)
        except ValueError:
            # Handle February 29 for non-leap years by using March 1
            birthday = birthdate.replace(year=today.year, month=3, day=1)

        # Calculate the age with floating-point precision
        age = today.year - birthdate.year + ((today - birthday).days / 365.0)
        return age


class Race(models.Model):
    name = models.CharField(max_length=255)
    championship = models.ForeignKey(Championship, on_delete=models.RESTRICT, related_name='races', null=True)
    round = models.IntegerField()
    country = CountryField()
    circuit = models.ForeignKey(Circuit, on_delete=models.RESTRICT, related_name='races', null=True)
    datetime = models.DateTimeField()
    fp1_datetime = models.DateTimeField(null=True, blank=True)
    fp2_datetime = models.DateTimeField(null=True, blank=True)
    fp3_datetime = models.DateTimeField(null=True, blank=True)
    quali_datetime = models.DateTimeField(null=True, blank=True)
    sprint_shootout_datetime = models.DateTimeField(null=True, blank=True)
    sprint_datetime = models.DateTimeField(null=True, blank=True)
    fantasy_ready = models.BooleanField(default=False)
    wikilink = models.URLField(blank=True)
    drivers = models.ManyToManyField(Driver, through='RaceDriver', related_name='attended_races')

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['championship', 'round'], name='unique_championship_round'),
        ]
        ordering = ["-datetime"]

    def __str__(self):
        return f"{self.championship.year} {self.name}"

    def get_absolute_url(self):
        return reverse(
            "formula:race_detail",
            kwargs={'series': self.championship.series, 'year': self.championship.year, "round": self.round}
        )

    def get_fantasy_url(self):
        return reverse(
            "formula:fantasy_race_results",
            kwargs={'series': self.championship.series, 'year': self.championship.year, "round": self.round}
        )

    def get_tahmin_url(self):
        return reverse(
            "formula:tahmin:race_tahmins",
            kwargs={'series': self.championship.series, 'year': self.championship.year, "round": self.round}
        )

    @cached_property
    def next(self):
        try:

f1t/apps/fantasy/templates/fantasy/driver_detail.html
{% extends 'base.html' %}
{% load static fantasy_tags %}

{% block title %}{{ driver.name }}{% endblock %}

{% block breadcrumb %}
  <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
  <li class="breadcrumb-item"><a href="{% url 'formula:all_driver_list' %}">Sürücüler</a></li>
  <li class="breadcrumb-item">{{ driver.name }}</li>
{% endblock %}

{% block stylesheet %}
  <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
{% endblock %}

{% block content %}
  <div class="container">
    <!-- Driver Name as Header -->
    <h3 class="text-center">{{ driver.name }}</h3>

    <!-- Three Column Layout -->
    <div class="row my-4">
        <!-- Column 1: Basic Information -->
        <div class="col-md-4">
            <ul class="list-unstyled">
                <li><strong>Numara:</strong> {{ driver.number|default_if_none:"" }}</li>
                <li><strong>Ülke:</strong> <i class="{{ driver.country.flag_css }}"></i> {{ driver.country.name }}</li>
                <li><strong>Kısaltma:</strong> {{ driver.code|default_if_none:"" }}</li>
                <li><strong>Doğum Tarihi:</strong> {{ driver.dob|default_if_none:"" }} ({{ driver.age|floatformat:1 }} yaş)</li>
            </ul>
        </div>

        <!-- Column 2: Race Statistics -->
        <div class="col-md-4">
            <ul class="list-unstyled">
                <li><a href="{% url 'formula:driver_results' driver.slug %}">{{ total_races }} yarış</a></li>
                <li><a href="{% url 'formula:driver_wins' driver.slug %}">{{ win }} galibiyet</a></li>
                <li><a href="{% url 'formula:driver_poles' driver.slug %}">{{ pole }} pol pozisyonu</a></li>
                <li><a href="{% url 'formula:driver_flaps' driver.slug %}">{{ flap }} en hızlı tur</a></li>
                <li><a href="{% url 'formula:driver_hattricks' driver.slug %}">{{ hattrick }} hat-trick</a></li>
            </ul>
        </div>

        <!-- Column 3: Podiums and Other Stats -->
        <div class="col-md-4">
            <ul class="list-unstyled">
                <li><a href="{% url 'formula:driver_podiums' driver.slug %}">{{ podium }} podyum</a></li>
                <li>{{ not_classified }} klasman dışı</li>
                <li><a href="{% url 'formula:driver_quali_h2h' driver.slug %}">Sıralama Karşılaştırmaları</a></li>
                <li><strong>İlk yarış:</strong> <a href="{{ first_race.get_absolute_url }}">{{ first_race }}</a></li>
                <li><strong>Son yarış:</strong> <a href="{{ last_race.get_absolute_url }}">{{ last_race }}</a></li>
            </ul>
        </div>
    </div>
</div>
<div class="table-responsive">
<table id="driver_results"
           class="table table-hover table-striped table-sm d-block d-lg-table text-center">
        <thead class="thead-inverse">
        <tr>
            <th>Sıra</th>
            {% for _ in positions %}
                <th>{{ forloop.counter }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tr>
            <td><b>Grid</b></td>
            {% for grid_count in grid_list %}
                <td>{{ grid_count|default_if_none:"" }}</td>
            {% endfor %}
        </tr>
        <tr>
            <td><b>Yarış</b></td>
            {% for result_count in result_list %}
                <td>{{ result_count|default_if_none:"" }}</td>
            {% endfor %}
        </tr>
    </table>
</div>
 <!-- Nav tabs -->
    {% include "fantasy/nav-tabs.html" %}
    <!-- Tab panes -->
    <div class="tab-content">
        {% for tab_id in tabs %}
            <div class="tab-pane {% if forloop.first %}show active{% else %}fade{% endif %}"
                 id="{{ tab_id }}">

                <br/>
                <div class="table-responsive">
                <table id="results_by_year_{{ tab_id }}"
                       class="table table-bordered table-sm d-block d-lg-table">
                    <thead class="thead-inverse">
                    <tr>
                        <th class="text-center">Şampiyona</th>
                        {% for _ in race_range %}
                            <th class="text-center">{{ forloop.counter }}</th>
                        {% endfor %}
                    </tr>
                    </thead>
                    {% for championship, results_by_year in race_results_dict.items %}
                        <tr>
                            <td class="text-center"><b><a
                                href="{{ championship.get_absolute_url }}">{{ championship.short_str|upper}}</a></b></td>
                            {% for race_driver in results_by_year %}
                                <td class="text-center">
                                    {{ race_driver|call_or_get_attr:tab_id|default_if_none:"-" }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                </table>
                </div>
            </div>

        {% endfor %}
    </div>
{% endblock %}


{% block javascript %}
    <script>
        {% for tab_id in tabs %}
                $(document).ready(function () {
                    $("#results_by_year_{{ tab_id }} td:not(:first-child)").each(function () {
                        var data = $(this).text();
                        var data_int = parseInt(data);

                        if (data_int === 1) {
                            $(this).addClass('bg_winner');
                        } else if (data_int === 2) {
                            $(this).addClass('bg_second');
                        } else if (data_int === 3) {
                            $(this).addClass('bg_third');
                        } else if (4 <= data_int && data_int <= 10) {
                            $(this).addClass('bg_points');
                        } else if (data_int > 10) {
                            $(this).addClass('bg_classified');
                        }
                    });
                });
            {% endfor %}

    </script>

{% endblock %}

f1t/apps/fantasy/templates/fantasy/raceteam_form.html
{% extends 'base.html' %}
{% load form_tags widget_tweaks fantasy_tags %}

{% block title %}Yeni Takım{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.championship.series %}">{{ championship.get_series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:race_list' championship.series championship.year %}">{{ championship.year }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:team_list' championship.series championship.year %}">Fantasy Lig</a></li>
    <li class="breadcrumb-item">Yeni Takım</li>
{% endblock %}

{% block content %}
    <h3>YENİ TAKIM KUR - <a href="{{ view.race.get_fantasy_url }}">{{ view.race.name }}</a></h3>
    <li>Kadronuzda en fazla <b>{{ max_drivers_in_team }} sürücü</b> olabilir, kadronuzu buna göre oluşturun.</li>
    <li>Bütçenizi <b>({{ STARTING_BUDGET|with_currency }})</b> aşmayın.</li>
    <li>Taktiğinizi kurallarda anlatıldığı üzere seçin.</li>
    <li>Kadronuzu gönderdikten sonra düzenlemek istiyorsanız süresonuna kadar buradan düzenleyebilirsiniz.</li>
    <li>İşlemlerinizi <b>{{ view.race.fp1_datetime|default_if_none:"???" }}</b> tarihine kadar yapabilirsiniz.</li>
    <br/>
        {% csrf_token %}
        {% include 'includes/form.html' %}
        <button type="submit" class="btn btn-success">Gönder</button>
        <button type="reset" class="btn btn-primary ms-2" id="deselect">Değişiklikleri Geri Al</button>
    </form>
{% endblock %}

{% block javascript %}
    <script>
        $(document).ready(function () {
            $('input[name="race_drivers"]').each(function () {
                $(this).attr("class", "")
            });
            $('#id_tactic').addClass('form-select');
            function sumit() {
                let budget = {{ STARTING_BUDGET|stringformat:".1f" }};
                let sum = 0;
                $('input[name="race_drivers"]:checked').each(function () {
                    sum += parseFloat($(this).attr("price"));
                });
                budget = Math.round((budget - sum + Number.EPSILON) * 10) / 10;
                $('#id_budget').val(budget);
            }

            sumit();

            $('#id_race_drivers').change(function () {
                sumit();
            });
        });
    </script>
{% endblock %}

f1t/apps/fantasy/templates/fantasy/stats_drivers_most_finished.html
{% extends 'fantasy/stats_drivers_base.html' %}
{% block title %}Finiş İstatistikleri{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.series %}">{{ view.series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:stats_series' view.series %}">İstatistikler</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:stats_drivers' view.series %}">Sürücüler</a></li>
    <li class="breadcrumb-item">En Çok Finiş</li>
{% endblock %}

{% block stats_table %}
    <div class="table-responsive">
    <table id="driver_results"
         class="table table-borderless d-block compact small stripe hover cell-border order-column justify-content-center text-center text-nowrap">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Sürücü</th>
            <th>Finişler</th>
        </tr>
        </thead>
        <tbody>
        {% for driver in driver_list %}
            <tr>
                <td></td>
                <td><a href="{{ driver.get_absolute_url }}">{{ driver.name }}</a></td>
                <td><a href="{% url 'formula:driver_results' driver.slug %}">{{ driver.race_count }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

f1t/apps/fantasy/templates/fantasy/stats_drivers_most_podiums.html
{% extends 'fantasy/stats_drivers_base.html' %}
{% block title %}Podyum İstatistikleri{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
	<li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.series %}">{{ view.series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:stats_series' view.series %}">İstatistikler</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:stats_drivers' view.series %}">Sürücüler</a></li>
    <li class="breadcrumb-item">En Çok Podyum</li>
{% endblock %}

{% block stats_table %}
    <div class="table-responsive">
    <table id="driver_results"
         class="table table-borderless d-block compact small stripe hover cell-border order-column justify-content-center text-center text-nowrap">
        <thead class="thead-inverse">
        <tr>
            <th>#</th>
            <th>Sürücü</th>
            <th>Podyum</th>
        </tr>
        </thead>
        <tbody>
        {% for driver in driver_list %}
            <tr>
                <td></td>
                <td><a href="{{ driver.get_absolute_url }}">{{ driver.name }}</a></td>
                <td><a href="{% url 'formula:driver_podiums' driver.slug %}">{{ driver.podium_count }}</a></td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
    </div>
{% endblock %}

f1t/apps/fantasy/templates/fantasy/stats_series.html
{% extends 'base.html' %}

{% block title %}Sürücü İstatistikleri{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' view.series %}">{{ view.series_display }}</a></li>
    <li class="breadcrumb-item">İstatistikler</li>
{% endblock %}

{% block content %}
    <ul>
		<li><a href="{% url "formula:stats_drivers" view.series %}" class="card-link">Sürücü İstatistikleri</a></li>
	</ul>
{% endblock %}