f1t/apps/fantasy/urls.py
from django.urls import include, path

from . import views
from .views import JolpicaCheckAPIView

app_name = "formula"
urlpatterns = [
    # Formula paths
    path('circuits/', views.CircuitListView.as_view(), name='circuit_list'),
    path('circuits/<pk>/', views.CircuitDetailView.as_view(), name='circuit_detail'),

    path('drivers/', views.AllDriverListView.as_view(), name='all_driver_list'),
    path('drivers/<slug>/', views.DriverDetailView.as_view(), name='driver_detail'),
    path('drivers/<slug>/races/', views.DriverResultsView.as_view(), name='driver_results'),
    path('drivers/<slug>/wins/', views.DriverWinsView.as_view(), name='driver_wins'),
    path('drivers/<slug>/poles/', views.DriverPolesView.as_view(), name='driver_poles'),
    path('drivers/<slug>/flaps/', views.DriverFastestLapsView.as_view(), name='driver_flaps'),
    path('drivers/<slug>/hattricks/', views.DriverHatTricksView.as_view(), name='driver_hattricks'),
    path('drivers/<slug>/podiums/', views.DriverPodiumsView.as_view(), name='driver_podiums'),
    path('drivers/<slug>/quali_h2h/', views.DriverHeadToHeadView.as_view(), name='driver_quali_h2h'),

    path('constructors/', views.ConstructorListView.as_view(), name='constructor_list'),
    path('constructors/<slug>/', views.ConstructorDetailView.as_view(), name='constructor_detail'),

    # Series Stats
    path('<str:series>/stats/', views.StatsForSeriesView.as_view(), name='stats_series'),
    path('<str:series>/stats/drivers/', views.StatsForDriverTemplateView.as_view(), name='stats_drivers'),
    path('<str:series>/stats/drivers/wins/', views.StatsForDriverWinView.as_view(), name='stats_driver_wins'),
    path('<str:series>/stats/drivers/poles/', views.StatsForDriverPoleView.as_view(), name='stats_driver_poles'),
    path('<str:series>/stats/drivers/podiums/', views.StatsForDriverPodiumView.as_view(), name='stats_driver_podiums'),
    path('<str:series>/stats/drivers/races/', views.StatsForDriverRaceView.as_view(), name='stats_driver_races'),
    path('<str:series>/stats/drivers/without_win/', views.StatsForDriverWithoutWinView.as_view(), name='stats_driver_without_win'),
    path('<str:series>/stats/drivers/finishes/', views.StatsForDriverFinishedView.as_view(), name='stats_driver_finishes'),

    # Season paths
    path('<str:series>/', views.SeasonsListView.as_view(), name='season_list'),
    path('<str:series>/<int:year>/stats/', views.SeasonStatsView.as_view(), name='season_stats'),
    path('<str:series>/<int:year>/stats/supergrid/', views.SeasonSupergridView.as_view(), name='season_supergrid'),
    path('<str:series>/<int:year>/stats/quali_h2h/', views.SeasonHeadToHeadView.as_view(), name='season_quali_h2h'),
    path('<str:series>/<int:year>/', views.RaceListView.as_view(), name='race_list'),
    path('<str:series>/<int:year>/last/', views.LastRaceRedirectView.as_view(), name='redirect_last_race'),
    path('<str:series>/<int:year>/<int:round>/', views.RaceDetailView.as_view(), name='race_detail'),
    path('<str:series>/<int:year>/<int:round>/fantasy/', views.RaceFantasyView.as_view(), name='fantasy_race_results'),
    path('<str:series>/<int:year>/last/fantasy/', views.LastRaceFantasyRedirectView.as_view(), name='redirect_last_fantasy_result'),
    path('<str:series>/<int:year>/<int:round>/edit/', views.RaceDriverUpdateView.as_view(), name='race_edit'),
    path('<str:series>/<int:year>/<int:round>/fantasy/edit/', views.PriceUpdateView.as_view(), name='price_edit'),

    # Fantasy paths
    path('<str:series>/<int:year>/teams/', views.FantasyStandingsView.as_view(), name='team_list_deprecated'),
    path('<str:series>/<int:year>/fantasy/', views.FantasyStandingsView.as_view(), name='team_list'),
    path('<str:series>/<int:year>/fantasy/stats/', views.FantasyStatsView.as_view(), name='driver_stats'),
    path('<str:series>/<int:year>/teams/new/', views.NewTeamView.as_view(), name='new_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/new/', views.NewTeamView.as_view(), name='new_team_form'),
    path('<str:series>/<int:year>/teams/edit/', views.EditTeamView.as_view(), name='edit_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/edit/', views.EditTeamView.as_view(), name='edit_team_form'),
    path('<str:series>/<int:year>/teams/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team_deprecated'),
    path('<str:series>/<int:year>/fantasy/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team'),
    path('<str:series>/<int:year>/teams/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail_deprecated'),
    path('<str:series>/<int:year>/fantasy/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail'),

    # API paths
    path('api/jolpica_check/', JolpicaCheckAPIView.as_view(), name='jolpica-check-api'),

    # Tahmin ligi paths
    path('<str:series>/<int:year>/', include("f1t.apps.tahmin.urls")),
]

f1t/apps/tahmin/urls.py
from django.urls import path

from . import views

app_name = "tahmin"
urlpatterns = [
    path('last/tahmin/', views.LastRaceRedirectView.as_view(), name='redirect_last_race'),
    path('<int:round>/tahmin/', views.RaceTahminView.as_view(), name='race_tahmins'),
    path('tahmin/', views.TeamListView.as_view(), name='team_list'),
    path('tahmin/new/', views.NewTahminView.as_view(), name='new_team_form'),
]

f1t/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.conf import settings
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from .views import HomeView, ContactView
from .urlresolvers import solid_i18n_patterns

patterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("f1t.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("contact/", ContactView.as_view(), name='contact'),
    path("greenflag/", include("f1t.apps.greenflag.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("", include("f1t.apps.season_predictions.urls")),
    path("", include("f1t.apps.driver_ranks.urls")),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('pwa.urls')),
    path('', HomeView.as_view(), name='home'),
    path("", include("f1t.apps.fantasy.urls")),
    path("", include("f1t.apps.ratings.urls")),
]

if settings.DEBUG:
    patterns.append(path('__debug__/', include('debug_toolbar.urls')))

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n"))
]
urlpatterns += solid_i18n_patterns(*patterns)

f1t/apps/tahmin/models.py
from django.contrib.auth.models import User
from django.db import models
from django.utils.functional import cached_property

from ..fantasy.models import Race, Driver, RaceDriver, Championship


class Question(models.Model):
    QUESTION_CHOICES = [
        ("A", "A"),
        ("B", "B"),
        ("C", "C"),
        ("D", "D"),
    ]
    race = models.ForeignKey(Race, on_delete=models.RESTRICT, related_name='questions', null=True)
    text = models.TextField()
    choice_A = models.CharField(max_length=64)
    point_A = models.PositiveSmallIntegerField()
    choice_B = models.CharField(max_length=64)
    point_B = models.PositiveSmallIntegerField()
    choice_C = models.CharField(null=True, blank=True, max_length=64)
    point_C = models.PositiveSmallIntegerField(null=True, blank=True)
    choice_D = models.CharField(null=True, blank=True, max_length=64)
    point_D = models.PositiveSmallIntegerField(null=True, blank=True)
    answer = models.CharField(
        max_length=1,
        choices=QUESTION_CHOICES,
        null=True,
        blank=True
    )

    class Meta:
        ordering = ["race"]

    def __str__(self):
        return f"{self.race} - {self.form_str()}"

    def form_str(self):
        result = f"{self.text}\n"
        for char, _ in self.QUESTION_CHOICES:
            choice = getattr(self, f"choice_{char}")
            point = getattr(self, f"point_{char}")
            if choice:
                result += f"\n{char}) {choice} [{point} puan]"
        return result

    @cached_property
    def point(self):
        return getattr(self, f"point_{self.answer}", 0)


class Tahmin(models.Model):
    race = models.ForeignKey(Race, on_delete=models.CASCADE, related_name='tahmins')
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tahmins')
    prediction_1 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_1')
    prediction_2 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_2')
    prediction_3 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_3')
    prediction_4 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_4')
    prediction_5 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_5')
    prediction_6 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_6')
    prediction_7 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_7')
    prediction_8 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_8')
    prediction_9 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_9')
    prediction_10 = models.ForeignKey(RaceDriver, on_delete=models.CASCADE, related_name='predictions_10')
    answer_1 = models.CharField(
        max_length=1,
        choices=Question.QUESTION_CHOICES
    )
    answer_2 = models.CharField(
        max_length=1,
        choices=Question.QUESTION_CHOICES
    )

    class Meta:
        constraints = [
            models.UniqueConstraint(fields=['race', 'user'], name='unique_tahmin'),
        ]
        ordering = [
            "race",
            "user__first_name"
        ]

    def __str__(self):
        return f"{self.race}-{self.user.get_full_name()}"

    def predicted_racedrivers(self):
        for position in range(1, 11):
            yield position, getattr(self, f"prediction_{position}")

    def predicted_answers(self):
        for idx, question in enumerate(self.race.questions.all()[:2], 1):
            yield getattr(self, f"answer_{idx}"), question

    def total_point(self):
        total = 0
        for position, predicted_race_driver in self.predicted_racedrivers():
            total += predicted_race_driver.tahmin_score(position)
        for predicted_answer, question in self.predicted_answers():
            if predicted_answer == question.answer:
                total += question.point
        return total

f1t/apps/tahmin/forms.py
from django import forms

from .models import Tahmin, Question


class RaceDriverChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, racedriver):
        return racedriver.driver


class NewTahminForm(forms.ModelForm):
    class Meta:
        model = Tahmin
        exclude = ["race", "user"]

    def __init__(self, current_race, *args, **kwargs):
        super().__init__(*args, **kwargs)
        race_drivers = current_race.driver_instances.select_related(
            "driver"
        )
        for idx in range(1, 11):
            self.fields[f"prediction_{idx}"] = RaceDriverChoiceField(
                label=f"{idx}. Sürücü",
                queryset=race_drivers
            )
        self.fields["answer_1"].label = "11. Soru henüz oluşturulmadı"
        self.fields["answer_1"].disabled = True
        self.fields["answer_2"].label = "12. Soru henüz oluşturulmadı"
        self.fields["answer_2"].disabled = True

        for idx, question in enumerate(current_race.questions.all()[:2], 1):
            self.fields[f"answer_{idx}"] = forms.ChoiceField(
                label=f"1{idx}. {question.form_str()}",
                widget=forms.RadioSelect,
                choices=Question.QUESTION_CHOICES[:4 if question.choice_D else (3 if question.choice_C else 2)],
            )

f1t/apps/tahmin/templates/tahmin/race_tahmins.html
{% extends 'base.html' %}
{% load static fantasy_tags admin_urls %}

{% block title %}{{ race }} - Tahmin Ligi{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item">
        <a href="{% url 'formula:season_list' view.championship.series %}">{{ view.championship.get_series_display }}</a></li>
    <li class="breadcrumb-item">
        <a href="{% url 'formula:race_list' view.championship.series view.championship.year %}">{{ view.championship.year }}</a></li>
    <li class="breadcrumb-item">
        <a href="{% url 'formula:race_detail' view.championship.series view.championship.year race.round%}">{{ race.name }}</a>
    </li>
	<li class="breadcrumb-item">
        Tahmin Ligi
    </li>
{% endblock %}

{% block content %}
    <div class="d-flex justify-content-between text-center my-4">
        <a class="btn btn-outline-primary {% if not race.previous %}disabled{% endif %}" href="{{ race.previous.get_tahmin_url }}">&larr; {{ race.previous|default_if_none:"" }}</a>
        <h3 class="text-center">{{ race.round }}. {{ race }} - Tahmin Ligi</h3>
        <a class="btn btn-outline-primary {% if not race.next %}disabled{% endif %}" href="{{ race.next.get_tahmin_url }}">{{ race.next|default_if_none:"" }} &rarr;</a>
    </div>

	<a href="{% url 'formula:tahmin:team_list' view.championship.series view.championship.year %}" class="btn btn-primary mb-4 me-2">Genel Klasman</a>

    {% if before_race %}
        <div class="alert alert-warning" role="alert">
            <img src="{% static 'tahmin/really3dcasio.jpg' %}" class="rounded mx-auto d-block" alt="Uyarı!">
            <h2 class="text-center">
                Üyelerimizin yaptığı tahminler yarış saatinden sonra görünür olacaktır.</h2>
            <p class="text-center">Yaptığınız tahmini görmek ya da yeni tahmin yapmak için:</p>
        </div>
        <div class="row justify-content-center">
            <a href="{% url 'formula:tahmin:new_team_form' view.championship.series view.championship.year %}" class="btn btn-primary">Tahmin Yap</a>
        </div>
    {% else %}
        {% if user.is_superuser %}
            <a href="{% url 'formula:race_edit' view.championship.series view.championship.year race.round %}" class="btn btn-secondary mb-4 me-2">Sonuç Gir</a>
            {% if race.questions.all.0 %}
                <a href="{% url opts|admin_urlname:'change' race.questions.all.0.pk %}" class="btn btn-secondary mb-4 me-2">1. Soruyu Değiştir</a>
            {% endif %}
            {% if race.questions.all.1 %}
                <a href="{% url opts|admin_urlname:'change' race.questions.all.1.pk %}" class="btn btn-secondary mb-4 me-2">2. Soruyu Değiştir</a>
            {% endif %}
        {% endif %}
    <div class="table-responsive">
    <table id="top10"
           class="table d-block compact small stripe hover cell-border order-column justify-content-center text-center text-nowrap">
        <thead class="thead-inverse">
        <tr>
            <th>Sıra</th>
            {% for _ in "123456789012" %}
                <th>{{ forloop.counter }}</th>
            {% endfor %}
        </tr>
        </thead>
        <tr>
            <td><b>Sürücü</b></td>
            {% for racedriver in race.top10 %}
                <td><b> {{ racedriver.driver.code|title }} </b></td>
            {% endfor %}
            <td>{{ race.questions.all.0.answer|default_if_none:"" }}</td>
            <td>{{ race.questions.all.1.answer|default_if_none:"" }}</td>
        </tr>
        <tr>
            <td><b>Doğru Tahmin Sayısı</b></td>
            {% for count in tahmin_counts %}
                <td> {{ count }} </td>
            {% endfor %}
            <td>{{ tahmin_count_q1|default_if_none:"" }}</td>
            <td>{{ tahmin_count_q2|default_if_none:"" }}</td>
        </tr>
        <tr>
            <td><b>Puan</b></td>
            {% for point in tahmin_points %}
                <td> {{ point }} </td>
            {% endfor %}
            <td>{{ race.questions.all.0.point|default_if_none:"-" }}</td>
            <td>{{ race.questions.all.1.point|default_if_none:"-" }}</td>
        </tr>
    </table>
    </div>

        <ol>
            {% for question in race.questions.all %}
                <li>{{ question.form_str|linebreaks }}</li>
            {% endfor %}
        </ol>
    <div class=table-responsive>
    <table id="table_race_detail"
           class="table table-borderless d-block compact small stripe hover cell-border order-column justify-content-center text-center text-nowrap">
        <thead class="thead-inverse">
        <tr>
            <th>Sıra</th>
            <th>Üye</th>
            {% for _ in "123456789012" %}
                <th>{{ forloop.counter }}</th>
            {% endfor %}
            <th>Toplam</th>
        </tr>
        </thead>

        <tbody>
        {% for tahmin in tahmin_list %}
            <tr>
                <td></td>
                <td><a href="#">{{ tahmin.user.get_full_name }}</a></td>
                {% for position, racedriver in tahmin.predicted_racedrivers %}
                    <td {% if racedriver.result == position %}style="background-color: #99ff9c"{% endif %}>
                        {{ racedriver.driver.code|title }}
                    </td>
                {% endfor %}
                {% for predicted_answer, question in tahmin.predicted_answers %}
                    <td {% if predicted_answer == question.answer %}style="background-color: #99ff9c"{% endif %}>
                        {{ predicted_answer }}
                    </td>
                {% endfor %}
                <td><b>{{ tahmin.total_point }}</b></td>
            </tr>
        {% endfor %}

        </tbody>
    </table>
    </div>

    <h4 class="my-3">Tahmin Sayıları</h4>
    <div class=table-responsive>
    <table id="table_tahmin_count_matrix"
           class="table table-borderless d-block compact small stripe hover cell-border order-column justify-content-center text-center text-nowrap">
        <thead class="thead-inverse">
        <tr>
            <th>Sıra</th>
            <th>Grid</th>
            <th>Sürücü</th>
            {% for _ in "1234567890" %}
                <th>{{ forloop.counter }}</th>
            {% endfor %}
            <th>Toplam</th>
        </tr>
        </thead>

        <tbody>
        {% for race_driver, tahmin_count_list in tahmin_count_matrix.items %}
            <tr>
                <td>{{ race_driver.result|default_if_none:"-" }}</td>
                <td>{{ race_driver.grid|default_if_none:"-" }}</td>
                <td style="background-color: {{ race_driver.championship_constructor.bgcolor }}; color: {{ race_driver.championship_constructor.fontcolor }}">
                    <a style="color: {{ race_driver.championship_constructor.fontcolor }}" href="{% url 'formula:driver_detail' race_driver.driver.slug %}"><b>{{ race_driver.driver }}</b></a>
                </td>
                {% for count in tahmin_count_list %}
                    <td style="{% if forloop.counter == race_driver.result and race_driver.result <= 10 %}font-weight: bold; color: mediumblue;{% endif %}">
                        {{ count }}
                    </td>
                {% endfor %}
            </tr>
        {% endfor %}

        </tbody>
    </table>
    </div>
    {% endif %}
{% endblock %}

{% block javascript %}
    <script>

        $(document).ready(function () {
            var table = $("#table_race_detail").DataTable(
                {
                    language: {
                        "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json"
                    },
                    paging: false,
                    "order": [[14, 'desc']],
                    "info": false,
                    columnDefs: [
                        {
                            className: "dt-center",
                            targets: "_all"
                        },
                        {
                            searchable: false,
                            orderable: false,
                            targets: 0,
                        },
                    ]
                }
            );
            table.on('init.dt', function () {
                    let i = 1;
                    table.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
                        this.data("<b>"+ i++ +"</b>");
                    });
                }).draw();
            var matrix = $("#table_tahmin_count_matrix").DataTable(
                {
                    language: {
                        "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json"
                    },
                    paging: false,
                    "info": false,
                    searching: false,
                    order: [],
                    columnDefs: [
                        {
                            className: "dt-center",
                            targets: "_all"
                        }
                    ]
                }
            );
            $("#table_tahmin_count_matrix tbody td").not(":nth-child(1), :nth-child(2), :nth-child(3), :nth-child(14), :empty").colorize();
            $("#table_tahmin_count_matrix tbody td:nth-child(14)").colorize({theme: "one-color"});
        });

    </script>

{% endblock %}

f1t/apps/tahmin/templates/tahmin/team_list.html
{% extends 'base.html' %}
{% load static fantasy_tags %}

{% block title %}Tahmin {{ championship }} Genel Klasman{% endblock %}

{% block stylesheet %}
    <link rel="stylesheet" href="{% static 'flags/sprite-hq.css' %}">
{% endblock %}

{% block breadcrumb %}
    <li class="breadcrumb-item"><a href="{% url 'home' %}">Ana Sayfa</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:season_list' championship.series %}">{{ championship.get_series_display }}</a></li>
    <li class="breadcrumb-item"><a href="{% url 'formula:race_list' championship.series championship.year %}">{{ championship.year }}</a></li>
    <li class="breadcrumb-item">Tahmin Ligi</li>
{% endblock %}

{% block content %}
	<div class="d-flex justify-content-between my-4">
        <a class="btn btn-outline-primary {% if not championship.previous or not championship.previous.is_tahmin %}disabled{% endif %}" href="{% if not championship.previous or not championship.previous.is_tahmin %}#{% else %}{% url 'formula:tahmin:team_list' championship.series championship.previous.year %}{% endif %}">&larr; {{ championship.previous.short_str|upper|default_if_none:"" }}</a>
        <h3 class="text-center">{{ championship.short_str|upper }} Sezonu Tahmin Ligi</h3>
        <a class="btn btn-outline-primary {% if not championship.next or not championship.next.is_tahmin %}disabled{% endif %}" href="{% if not championship.next or not championship.next.is_tahmin %}#{% else %}{% url 'formula:tahmin:team_list' championship.series championship.next.year %}{% endif %}">{{ championship.next.short_str|upper|default_if_none:"" }} &rarr;</a>
    </div>

	<div class="btn-toolbar my-4" role="toolbar" aria-label="Toolbar with button groups">
		{% if championship.is_tahmin %}
      <div class="d-flex gap-2" role="group" aria-label="Menu Group Tahmin">
		<a href="{% url "django.contrib.flatpages.views.flatpage" url="tahmin/" %}" class="btn btn-outline-primary">Tahmin Ligi Nedir</a>
        <a href="{% url 'formula:tahmin:new_team_form' championship.series championship.year %}"
           class="btn btn-outline-primary">Yeni Tahmin</a>
		<a href="{% url 'formula:tahmin:redirect_last_race' championship.series championship.year %}"
           class="btn btn-outline-primary">Son Yarış Sonuçları</a>
      </div>
    {% endif %}
	</div>

    {% include "fantasy/race_range_selector.html" %}

    <!-- Nav tabs -->
    {% include "fantasy/nav-tabs.html" %}
    <!-- Tab panes -->
    <div class="tab-content">
        {% for tab_id in tabs %}
            <div class="tab-pane {% if forloop.first %}show active{% else %}fade{% endif %}"
                 id="{{ tab_id }}">
                <br/>
                <div class=table-responsive>
                <table id="table_{{ tab_id }}"
                       class="table table-borderless d-block compact small stripe hover cell-border order-column justify-content-center text-center text-nowrap">
                    <thead class="thead-inverse">
                    <tr>
                        <th>Sıra</th>
                        <th>Üye</th>
                        <th>Toplam</th>
                        {% for race in race_list %}
                            <th>
                                <a href="{{ race.get_tahmin_url }}"><i class="{{ race.country.flag_css }}"></i></a>
                            </th>
                        {% endfor %}
                    </tr>
                    </thead>
                    <tbody>

                    {% for user, tahmin_list in tahmin_race_user_matrix.items %}
                        <tr>
                            <td></td>
                            <td><a href="#">{{ user.get_full_name }}</a></td>
                            <td></td>

                            {% for tahmin in tahmin_list %}
                                <td>
                                    {{ tahmin|call_or_get_attr:tab_id|default_if_none:"-" }}
                                </td>
                            {% endfor %}
                        </tr>
                    {% endfor %}
                    </tbody>
                </table>
            </div>
                </div>
        {% endfor %}
    </div>

{% endblock %}

{% block javascript %}
    <script src="{% static 'fantasy/js/roundSelector.js' %}"></script>
    <script>
        $(document).ready(function () {
            // Initialize DataTables
            {% for tab_id in tabs %}
                var {{ tab_id }} = $("#table_{{ tab_id }}").DataTable(
                    {
                        language: {
                            "url": "https://cdn.datatables.net/plug-ins/1.13.2/i18n/tr.json"
                        },
                        paging: false,
                        "order": [[2, 'desc']],
                        "info": false,

                        columnDefs: [
                            {
                                className: "dt-center",
                                targets: "_all"
                            },
                            {
                                searchable: false,
                                orderable: false,
                                targets: 0,
                            },
                            {
                                render: function (data, type, row) {
                                    let result = 0.0;
                                    let num;
                                    let nan_count = 0;
                                    for (let i = 2; i < row.length; i++) {
                                        num = parseFloat(row[i].replace(',', '.'));
                                        if (isNaN(num)) {
                                            num = 0.0;
                                            nan_count += 1;
                                        }
                                        result += num;
                                    }
                                    {% if tab_id in 'qualy,grid,results' %}
                                        result /= row.length - 2 - nan_count;
                                        result = isNaN(result) ? "" : result;
                                    {% endif %}

                                    return "<b>" + result.toFixed(0) + "</b>";
                                },
                                targets: 2,
                            }
                        ]
                    }
                );
                {{ tab_id }}.on('init.dt', function () {
                    let i = 1;
                    {{ tab_id }}.cells(null, 0, { search: 'applied', order: 'applied' }).every(function (cell) {
                        this.data("<b>"+ i++ +"</b>");
                    });
                }).draw();
                $("#table_{{ tab_id }} tbody td").not(":nth-child(1),:nth-child(2), :empty").colorize();
            {% endfor %}
        });

    </script>

{% endblock %}