f1t/apps/fantasy/urls.py
from django.urls import include, path

from . import views
from .views import JolpicaCheckAPIView

app_name = "formula"
urlpatterns = [
    # Formula paths
    path('circuits/', views.CircuitListView.as_view(), name='circuit_list'),
    path('circuits/<pk>/', views.CircuitDetailView.as_view(), name='circuit_detail'),

    path('drivers/', views.AllDriverListView.as_view(), name='all_driver_list'),
    path('drivers/<slug>/', views.DriverDetailView.as_view(), name='driver_detail'),
    path('drivers/<slug>/races/', views.DriverResultsView.as_view(), name='driver_results'),
    path('drivers/<slug>/wins/', views.DriverWinsView.as_view(), name='driver_wins'),
    path('drivers/<slug>/poles/', views.DriverPolesView.as_view(), name='driver_poles'),
    path('drivers/<slug>/flaps/', views.DriverFastestLapsView.as_view(), name='driver_flaps'),
    path('drivers/<slug>/hattricks/', views.DriverHatTricksView.as_view(), name='driver_hattricks'),
    path('drivers/<slug>/podiums/', views.DriverPodiumsView.as_view(), name='driver_podiums'),
    path('drivers/<slug>/quali_h2h/', views.DriverHeadToHeadView.as_view(), name='driver_quali_h2h'),

    path('constructors/', views.ConstructorListView.as_view(), name='constructor_list'),
    path('constructors/<slug>/', views.ConstructorDetailView.as_view(), name='constructor_detail'),

    # Series Stats
    path('<str:series>/stats/', views.StatsForSeriesView.as_view(), name='stats_series'),
    path('<str:series>/stats/drivers/', views.StatsForDriverTemplateView.as_view(), name='stats_drivers'),
    path('<str:series>/stats/drivers/wins/', views.StatsForDriverWinView.as_view(), name='stats_driver_wins'),
    path('<str:series>/stats/drivers/poles/', views.StatsForDriverPoleView.as_view(), name='stats_driver_poles'),
    path('<str:series>/stats/drivers/podiums/', views.StatsForDriverPodiumView.as_view(), name='stats_driver_podiums'),
    path('<str:series>/stats/drivers/races/', views.StatsForDriverRaceView.as_view(), name='stats_driver_races'),
    path('<str:series>/stats/drivers/without_win/', views.StatsForDriverWithoutWinView.as_view(), name='stats_driver_without_win'),
    path('<str:series>/stats/drivers/finishes/', views.StatsForDriverFinishedView.as_view(), name='stats_driver_finishes'),

    # Season paths
    path('<str:series>/', views.SeasonsListView.as_view(), name='season_list'),
    path('<str:series>/<int:year>/stats/', views.SeasonStatsView.as_view(), name='season_stats'),
    path('<str:series>/<int:year>/stats/supergrid/', views.SeasonSupergridView.as_view(), name='season_supergrid'),
    path('<str:series>/<int:year>/stats/quali_h2h/', views.SeasonHeadToHeadView.as_view(), name='season_quali_h2h'),
    path('<str:series>/<int:year>/', views.RaceListView.as_view(), name='race_list'),
    path('<str:series>/<int:year>/last/', views.LastRaceRedirectView.as_view(), name='redirect_last_race'),
    path('<str:series>/<int:year>/<int:round>/', views.RaceDetailView.as_view(), name='race_detail'),
    path('<str:series>/<int:year>/<int:round>/fantasy/', views.RaceFantasyView.as_view(), name='fantasy_race_results'),
    path('<str:series>/<int:year>/last/fantasy/', views.LastRaceFantasyRedirectView.as_view(), name='redirect_last_fantasy_result'),
    path('<str:series>/<int:year>/<int:round>/edit/', views.RaceDriverUpdateView.as_view(), name='race_edit'),
    path('<str:series>/<int:year>/<int:round>/fantasy/edit/', views.PriceUpdateView.as_view(), name='price_edit'),

    # Fantasy paths
    path('<str:series>/<int:year>/teams/', views.FantasyStandingsView.as_view(), name='team_list_deprecated'),
    path('<str:series>/<int:year>/fantasy/', views.FantasyStandingsView.as_view(), name='team_list'),
    path('<str:series>/<int:year>/fantasy/stats/', views.FantasyStatsView.as_view(), name='driver_stats'),
    path('<str:series>/<int:year>/teams/new/', views.NewTeamView.as_view(), name='new_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/new/', views.NewTeamView.as_view(), name='new_team_form'),
    path('<str:series>/<int:year>/teams/edit/', views.EditTeamView.as_view(), name='edit_team_form_deprecated'),
    path('<str:series>/<int:year>/fantasy/edit/', views.EditTeamView.as_view(), name='edit_team_form'),
    path('<str:series>/<int:year>/teams/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team_deprecated'),
    path('<str:series>/<int:year>/fantasy/me/', views.FantasyProfileRedirectView.as_view(), name='redirect_my_team'),
    path('<str:series>/<int:year>/teams/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail_deprecated'),
    path('<str:series>/<int:year>/fantasy/<str:username>/', views.FantasyUserProfileView.as_view(), name='team_detail'),

    # API paths
    path('api/jolpica_check/', JolpicaCheckAPIView.as_view(), name='jolpica-check-api'),

    # Tahmin ligi paths
    path('<str:series>/<int:year>/', include("f1t.apps.tahmin.urls")),
]

f1t/apps/greenflag/urls.py
from django.urls import include, path

from . import views

app_name = "greenflag"
urlpatterns = [
    path('', views.GreenFlagListView.as_view(), name='greenflag_list'),
    path('<int:pk>/', views.GreenFlagDetailView.as_view(), name='greenflag_detail'),
]

f1t/apps/ratings/urls.py
from django.urls import include, path

from . import views

app_name = "ratings"
urlpatterns = [
    # Yarışı Puanla paths
    path('<str:series>/<int:year>/puanla/', views.SeasonRatingView.as_view(), name='season_ratings'),
    path('<str:series>/puanla/', views.SeriesRatingView.as_view(), name='series_ratings'),
    path('<str:series>/<int:year>/<int:round>/puanla/', views.RatingCreateView.as_view(), name='create_ratings'),
]

f1t/apps/tahmin/urls.py
from django.urls import path

from . import views

app_name = "tahmin"
urlpatterns = [
    path('last/tahmin/', views.LastRaceRedirectView.as_view(), name='redirect_last_race'),
    path('<int:round>/tahmin/', views.RaceTahminView.as_view(), name='race_tahmins'),
    path('tahmin/', views.TeamListView.as_view(), name='team_list'),
    path('tahmin/new/', views.NewTahminView.as_view(), name='new_team_form'),
]

f1t/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.views.decorators.cache import cache_page
from django.views.decorators.vary import vary_on_cookie
from django.conf import settings
from django.contrib.flatpages.views import flatpage
from django.views.generic import TemplateView

from .views import HomeView, ContactView
from .urlresolvers import solid_i18n_patterns

patterns = [
    path('admin/clearcache/', include('clearcache.urls')),
    path('admin/', admin.site.urls),
    path("accounts/", include("f1t.apps.accounts.urls")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("contact/", ContactView.as_view(), name='contact'),
    path("greenflag/", include("f1t.apps.greenflag.urls")),
    path("pages/", include("django.contrib.flatpages.urls")),
    path("", include("f1t.apps.season_predictions.urls")),
    path("", include("f1t.apps.driver_ranks.urls")),
    path('mdeditor/', include('mdeditor.urls')),
    path('', include('pwa.urls')),
    path('', HomeView.as_view(), name='home'),
    path("", include("f1t.apps.fantasy.urls")),
    path("", include("f1t.apps.ratings.urls")),
]

if settings.DEBUG:
    patterns.append(path('__debug__/', include('debug_toolbar.urls')))

urlpatterns = [
    path("i18n/", include("django.conf.urls.i18n"))
]
urlpatterns += solid_i18n_patterns(*patterns)

f1t/apps/greenflag/models.py
from django.db import models
from django.urls import reverse

from f1t.apps.fantasy.models import Race
class GreenFlag(models.Model):
    race = models.OneToOneField(Race, on_delete=models.CASCADE, related_name='greenflag_instance')
    title = models.CharField(max_length=255)
    url = models.URLField()

    def __str__(self):
        return f"{self.race} Green Flag: {self.title}"

    def get_absolute_url(self):
        return reverse('greenflag:greenflag_detail', args=[self.pk])

f1t/apps/accounts/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(label="Adı", max_length=150)
    last_name = forms.CharField(label="Soyadı", max_length=150)

    class Meta:
        model = User
        fields = ("username", "first_name", "last_name",
                  "email", "password1", "password2")

f1t/forms.py
from django import forms
from django_recaptcha.fields import ReCaptchaField

class ContactForm(forms.Form):
    first_name = forms.CharField(max_length=50, label="Ad")
    last_name = forms.CharField(max_length=50, label="Soyad")
    email = forms.EmailField(label="E-posta")
    message = forms.CharField(widget=forms.Textarea, label="Mesaj")
    captcha = ReCaptchaField(label="Doğrulama")

f1t/apps/accounts/views.py
import logging

from django.contrib.auth import authenticate, login
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.models import User
from django.contrib.auth.views import RedirectURLMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import UpdateView, CreateView

from .forms import SignUpForm

logger = logging.getLogger("f1t")


class UserUpdateView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = User
    fields = ('first_name', 'last_name', 'email', )
    template_name = 'my_account.html'
    success_url = reverse_lazy('profile')
    success_message = "Profiliniz başarıyla güncellendi!"

    def get_object(self):
        return self.request.user


class SignUpView(SuccessMessageMixin, RedirectURLMixin, CreateView):
    """
    Allows the User to Create a New Account
    """
    form_class = SignUpForm
    template_name = "signup.html"
    next_page = reverse_lazy('home')
    success_message = "Üyeliğiniz başarıyla oluşturuldu!"

    def form_valid(self, form):
        valid = super().form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        new_user = authenticate(username=username, password=password)
        login(self.request, new_user)
        logger.info(f"NEW USER: {username} - {form.cleaned_data.get('first_name')} {form.cleaned_data.get('last_name')}")
        return valid

f1t/apps/driver_ranks/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Sum, Case, When, IntegerField, Q
from django.shortcuts import get_object_or_404, render
from django.utils import timezone
from django.views.generic import DetailView, ListView, TemplateView
from django.views.generic.edit import FormView

from .models import PollResponse
from .forms import DragDropRankForm
from f1t.apps.fantasy.models import Championship, Driver, Race

User = get_user_model()
DRIVER_RANK_POINTS = [25, 18, 15, 12, 10, 8, 6, 4, 2, 1, -1, -2, -4, -6, -8, -10, -12, -15, -18, -25]


class DriverPointsView(TemplateView):
    template_name = 'driver_ranks/driver_points.html'

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Create a Case statement to assign points based on position from PollResponse
        point_cases = Case(
            *[When(pollresponse__position=i + 1, then=DRIVER_RANK_POINTS[i]) for i in range(20)],
            default=0,
            output_field=IntegerField()
        )

        driver_points = Driver.objects.annotate(
            total_points=Sum(
                point_cases,
                filter=Q(pollresponse__championship=self.championship)
            )
        ).filter(
            total_points__isnull=False
        ).order_by('-total_points')

        context['driver_points'] = driver_points
        return context


class DragDropRankView(SuccessMessageMixin, LoginRequiredMixin, FormView):
    template_name = 'driver_ranks/drag_drop.html'
    form_class = DragDropRankForm
    success_message = "Sürücü sıralamanız başarıyla kaydedildi."

    def get_success_url(self):
        return self.request.path

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        # Fetch the championship object
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )

    def _is_past_deadline(self):
        try:
            race = self.championship.races.earliest("fp1_datetime")
            deadline = race.fp1_datetime
            return timezone.now() > deadline
        except Race.DoesNotExist:
            return True

    def get(self, request, *args, **kwargs):
        if self._is_past_deadline():
            return render(request, "expired.html", status=403)
        return super().get(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        if self._is_past_deadline():
            return render(request, "expired.html", status=403)
        return super().post(request, *args, **kwargs)

    def get_queryset(self):
        return Driver.objects.filter(
            race_instances__race__championship=self.championship
        ).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        race = self.championship.races.earliest("fp1_datetime")
        # Get base queryset
        drivers = self.get_queryset()

        # Check for existing poll response
        if self.request.user.is_authenticated:
            existing_response = PollResponse.objects.filter(
                user=self.request.user,
                championship=self.championship
            ).order_by('position')

            if existing_response.exists():
                # Get driver IDs in existing order
                ordered_ids = existing_response.values_list('driver_id', flat=True)

                # Preserve the order from the existing response
                preserved_order = Case(
                    *[When(id=driver_id, then=pos) for pos, driver_id in enumerate(ordered_ids)],
                    output_field=IntegerField()
                )
                drivers = drivers.order_by(preserved_order)
        context['drivers'] = drivers
        context['deadline'] = race.fp1_datetime
        return context

    def form_valid(self, form):
        driver_ids = form.cleaned_data['ranked_drivers']
        user = self.request.user
        user.pollresponse_set.filter(
            championship=self.championship
        ).delete()

        for position, driver_id in enumerate(driver_ids, start=1):
            PollResponse.objects.create(
                user=self.request.user,
                championship=self.championship,
                driver_id=driver_id,
                position=position
            )
        return super().form_valid(form)


class DriverRanksDetailView(DetailView):
    model = PollResponse
    template_name = 'driver_ranks/detail.html'
    context_object_name = 'user'

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        # Fetch the championship object
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )

    def get_object(self):
        return get_object_or_404(
            User,
            username=self.kwargs.get('username')
        )

    def _is_past_deadline(self):
        try:
            race = self.championship.races.earliest("fp1_datetime")
            deadline = race.fp1_datetime
            return timezone.now() > deadline
        except Race.DoesNotExist:
            return True

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        user = self.object
        user_responses = user.pollresponse_set.select_related('driver').filter(
            championship=self.championship
        ).order_by('position')

        context['processed_answers'] = user_responses
        return context


class DriverRankListView(ListView):
    template_name = 'driver_ranks/list.html'
    context_object_name = 'users'
    allow_empty = False

    def setup(self, request, *args, **kwargs):
        super().setup(request, *args, **kwargs)
        # Fetch the championship object
        self.championship = get_object_or_404(
            Championship,
            series=self.kwargs.get("series"),
            year=self.kwargs.get("year")
        )
    def get_queryset(self):
        return User.objects.filter(
            pollresponse__championship=self.championship
        ).distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['championship'] = self.championship
        return context

f1t/apps/greenflag/views.py
from django.shortcuts import get_object_or_404
from django.views.generic import ListView, DetailView

from f1t.apps.fantasy.models import Championship
from .models import GreenFlag


class GreenFlagListView(ListView):
    allow_empty = False
    template_name = "greenflag/greenflag_list.html"
    model = GreenFlag
    queryset = GreenFlag.objects.select_related('race', 'race__championship')


class GreenFlagDetailView(DetailView):
    template_name = "greenflag/greenflag_detail.html"
    model = GreenFlag

f1t/templates/includes/footer.html
{% load static %}

<footer>
  <div class="container-fluid bg-dark text-light py-5">
    <div class="container">
      <div class="row">
        <div class="col-sm-12 col-md-3 col-lg-3">
          <h5>Linkler</h5>
            <ul>
              <li><a href="{% url "contact" %}">Bize ulaşın!</a></li>
              <li><a href="{% url "django.contrib.flatpages.views.flatpage" url="changelog/" %}">Değişiklik güncesi</a></li>
              <li><a href="{% url "django.contrib.flatpages.views.flatpage" url="faq/" %}">Sık Sorulan Sorular</a></li>
            </ul>
        </div>
        <div class="col-sm-12 col-md-3 col-lg-3">
          <h5>Facebook Gruplarımıza Katılın</h5>
          <div class="d-grid gap-2">
          <a class="btn btn-social btn-facebook" href="https://facebook.com/groups/Formula1Turkiye">
            <i class="fa-brands fa-facebook-f"></i> Formula 1 Türkiye
          </a>
          <a class="btn btn-social btn-facebook" href="https://facebook.com/groups/FormulaETurkiye">
            <i class="fa-brands fa-facebook-f"></i> F2 + FE Türkiye
          </a>
            </div>
        </div>
        <div class="col-sm-12 col-md-6 col-lg-6">
          <h5>
            <img src="{% static "icons/apple-touch-icon.png" %}" width="30" height="30" alt="logo">
            Formula 1 Türkiye
          </h5>
          <p>Formula 1 Türkiye grubu ana sayfasına hoş geldiniz. Bu site, 4600'ü aşkın üyesiyle,
            aktifleştiği 2015 yılından bu yana Türkiye'nin en büyük Formula 1 Facebook grubu olan Formula 1 Türkiye'nin
            düzenlediği Fantasy ve Tahmin Ligleri için kurduğumuz web sitesidir. Dilerseniz Quiz Night, Yarışı Puanla ve
            Elo Sıralama Projesi gibi diğer ürünlerimize de bakabilirsiniz.</p>

        </div>
      </div>
    </div>
  </div>
</footer>

f1t/templates/includes/form.html
{% load form_tags widget_tweaks %}

{% if form.non_field_errors %}
  <div class="alert alert-danger" role="alert">
    {% for error in form.non_field_errors %}
      <p{% if forloop.last %} class="mb-0"{% endif %}>{{ error }}</p>
    {% endfor %}
  </div>
{% endif %}

{% for field in form %}
    {% if field.name == "captcha" and form.captcha %}
        <div class="mb-3">
            {{ form.captcha.label_tag|linebreaks }}
            {{ form.captcha }}  <!-- Render the captcha field -->
            {% for error in form.captcha.errors %}
                <div class="invalid-feedback d-block">
                    {{ error }}
                </div>
            {% endfor %}
        </div>
    {% else %}
  <div class="mb-3">
    {{ field.label_tag|linebreaks }}
    {% render_field field class=field|input_class %}
    {% for error in field.errors %}
      <div class="invalid-feedback">
        {{ error }}
      </div>
    {% endfor %}
    {% if field.help_text %}
      <small class="form-text text-muted">
        {{ field.help_text|safe }}
      </small>
    {% endif %}
  </div>
    {% endif %}
{% endfor %}

f1t/templates/includes/meta.html
{% load pwa %}
<meta charset="utf-8">
<meta http-equiv="Content-Type" content="text/html;charset=UTF-8">
<meta name="description"
      content="Formula 1 Türkiye grubu ana sayfasına hoş geldiniz. Bu site, 4600'ü aşkın üyesiyle, aktifleştiği 2015 yılından bu yana Türkiye'nin en büyük Formula 1 Facebook grubu olan Formula 1 Türkiye'nin düzenlediği Fantasy ve Tahmin Ligleri için kurduğumuz web sitesidir.">
<meta name=viewport" content="width=device-width, initial-scale=1.0">

<!-- PWA Meta -->
{% progressive_web_app_meta %}

<!-- Facebook Meta Tags -->
<meta property="og:site_name" content="Formula 1 Türkiye">
<meta property="og:title" content="Formula 1 Türkiye">
<meta property="og:image" content="https://formula1turkiye.pythonanywhere.com/static/icons/buzzinhornets.jpg">
<meta property="og:image:secure_url" content="https://formula1turkiye.pythonanywhere.com/static/icons/buzzinhornets.jpg">
<meta property="og:image:width" content="1200">
<meta property="og:image:height" content="650">
<meta property="og:url" content="https://formula1turkiye.pythonanywhere.com/">
<meta property="og:description"
      content="Formula 1 Türkiye ligleri ana sayfasına hoş geldiniz. Bu site, 4600'ü aşkın üyesiyle, aktifleştiği 2015 yılından bu yana Türkiye'nin en büyük Formula 1 Facebook grubu olan Formula 1 Türkiye'nin düzenlediği Fantasy ve Tahmin Ligleri için kurduğumuz web sitesidir.">
<meta property="og:type" content="website"/>
<meta property="og:locale" content="tr_TR"/>

<!-- Twitter Meta Tags -->
<meta name="twitter:card" content="summary_large_image">
<meta property="twitter:domain" content="formula1turkiye.pythonanywhere.com">
<meta property="twitter:url" content="https://formula1turkiye.pythonanywhere.com">
<meta name="twitter:title" content="Formula 1 Türkiye">
<meta name="twitter:description"
      content="Formula 1 Türkiye ligleri ana sayfasına hoş geldiniz. Bu site, 4600'ü aşkın üyesiyle, aktifleştiği 2015 yılından bu yana Türkiye'nin en büyük Formula 1 Facebook grubu olan Formula 1 Türkiye'nin düzenlediği Fantasy ve Tahmin Ligleri için kurduğumuz web sitesidir.">
<meta name="twitter:image" content="https://formula1turkiye.pythonanywhere.com/static/icons/buzzinhornets.jpg">

f1t/templates/includes/navbar.html
<nav class="navbar navbar-expand-md navbar-dark bg-dark" data-bs-theme="dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'home' %}">Formula 1 Türkiye</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#mainMenu"
                aria-controls="mainMenu" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="mainMenu">
          <ul class="navbar-nav">
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-bs-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">Seriler</a>
                  <div class="dropdown-menu" aria-labelledby="userMenu">
                      <a class="dropdown-item" href="{% url 'formula:season_list' 'f1' %}">Formula 1</a>
                      <a class="dropdown-item" href="{% url 'formula:season_list' 'f2' %}">Formula 2</a>
                  </div>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-bs-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">Verilerimiz</a>
                  <div class="dropdown-menu" aria-labelledby="userMenu">
                      <a class="dropdown-item" href="{% url "formula:stats_series" "f1" %}">F1 İstatistikleri</a>
                      <a class="dropdown-item" href="{% url 'formula:circuit_list' %}">Pistler</a>
                      <a class="dropdown-item" href="{% url 'formula:all_driver_list' %}">Sürücüler</a>
                      <a class="dropdown-item" href="{% url 'formula:constructor_list' %}">Markalar</a>
                  </div>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-bs-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                      Liglerimiz
                  </a>
                  <div class="dropdown-menu" aria-labelledby="userMenu">
                      <a class="dropdown-item" href="{% url 'formula:team_list' 'f1' '2025' %}">F1 Fantasy Lig 2025</a>
                      <a class="dropdown-item" href="{% url 'formula:team_list' 'f2' '2025' %}">F2 Fantasy Lig 2025</a>
                      <a class="dropdown-item" href="{% url 'formula:tahmin:team_list' 'f1' '2025' %}">F1 Tahmin Ligi 2025</a>
                  </div>
              </li>
              <li class="nav-item dropdown">
                  <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-bs-toggle="dropdown"
                     aria-haspopup="true" aria-expanded="false">
                      Ürünlerimiz
                  </a>
                  <div class="dropdown-menu" aria-labelledby="userMenu">
                      <a class="dropdown-item" href="{% url "django.contrib.flatpages.views.flatpage" url="elo/" %}">Elo Sıralama Projesi</a>
                      <a class="dropdown-item" href="{% url "ratings:series_ratings" "f1" %}">Yarışı Puanla</a>
                      <a class="dropdown-item" href="{% url "django.contrib.flatpages.views.flatpage" url="quiz/" %}">Quiz Night</a>
                      <a class="dropdown-item" href="{% url 'greenflag:greenflag_list' %}">Green Flag Dergisi</a>
                  </div>
              </li>
          </ul>
                      <div class="ms-auto d-flex gap-2 col-lg-3 justify-content-end text-nowrap">
            {% if user.is_authenticated %}
                <ul class="navbar-nav">
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="userMenu" data-bs-toggle="dropdown"
                           aria-haspopup="true" aria-expanded="false">
                            {{ user.username }}
                        </a>
                        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="userMenu">
                            <a class="dropdown-item" href="{% url 'profile' %}">Hesabım</a>
                            <a class="dropdown-item" href="{% url 'password_change' %}">Parolayı değiştir</a>
                            <div class="dropdown-divider"></div>
                            {% if user.is_staff %}
                                <a class="dropdown-item" href="{% url 'admin:index' %}">Yönetici sayfası</a>
                                <div class="dropdown-divider"></div>
                            {% endif %}
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button class="dropdown-item" type="submit">Çıkış yap</button>
                            </form>
                        </div>
                    </li>
                </ul>
            {% else %}
                    <a href="{% url 'login' %}" class="btn btn-outline-secondary">Giriş yap</a>
                    <a href="{% url 'signup' %}" class="btn btn-primary">Kaydol</a>
            {% endif %}
        </div>
        </div>
    </div>
</nav>